
package com.smw.wsc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-06-06T16:41:21.854+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
public final class SalesSoap_SalesSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempurl.org", "sales");

    private SalesSoap_SalesSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Sales.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Sales ss = new Sales(wsdlURL, SERVICE_NAME);
        SalesSoap port = ss.getSalesSoap();  
        
        {
        System.out.println("Invoking postmalldailysalessummary...");
        com.smw.wsc.Postmalldailysalessummaryrequest _postmalldailysalessummary_astrRequest = null;
        com.smw.wsc.Postmalldailysalessummaryresponse2 _postmalldailysalessummary__return = port.postmalldailysalessummary(_postmalldailysalessummary_astrRequest);
        System.out.println("postmalldailysalessummary.result=" + _postmalldailysalessummary__return);


        }
        {
        System.out.println("Invoking getcompanyname...");
        java.lang.String _getcompanyname__return = port.getcompanyname();
        System.out.println("getcompanyname.result=" + _getcompanyname__return);


        }
        {
        System.out.println("Invoking postsalescreate...");
        com.smw.wsc.Postsalescreaterequest _postsalescreate_astrRequest = null;
        com.smw.wsc.Postsalescreateresponse2 _postsalescreate__return = port.postsalescreate(_postsalescreate_astrRequest);
        System.out.println("postsalescreate.result=" + _postsalescreate__return);


        }
        {
        System.out.println("Invoking postesalescreate...");
        com.smw.wsc.Postesalescreaterequest _postesalescreate_astrRequest = null;
        com.smw.wsc.Postesalescreateresponse2 _postesalescreate__return = port.postesalescreate(_postesalescreate_astrRequest);
        System.out.println("postesalescreate.result=" + _postesalescreate__return);


        }
        {
        System.out.println("Invoking getversion...");
        java.lang.String _getversion__return = port.getversion();
        System.out.println("getversion.result=" + _getversion__return);


        }
        {
        System.out.println("Invoking postdailysalesestimatecreate...");
        com.smw.wsc.Postdailysalesestimatecreaterequest _postdailysalesestimatecreate_astrRequest = null;
        com.smw.wsc.Postdailysalesestimatecreateresponse2 _postdailysalesestimatecreate__return = port.postdailysalesestimatecreate(_postdailysalesestimatecreate_astrRequest);
        System.out.println("postdailysalesestimatecreate.result=" + _postdailysalesestimatecreate__return);


        }
        {
        System.out.println("Invoking postdailysalessummary2...");
        com.smw.wsc.Postdailysalessummary2Request _postdailysalessummary2_astrRequest = null;
        com.smw.wsc.Postdailysalessummary2Response2 _postdailysalessummary2__return = port.postdailysalessummary2(_postdailysalessummary2_astrRequest);
        System.out.println("postdailysalessummary2.result=" + _postdailysalessummary2__return);


        }
        {
        System.out.println("Invoking testAPlusB...");
        int _testAPlusB_alValue1 = 0;
        int _testAPlusB_alValue2 = 0;
        int _testAPlusB__return = port.testAPlusB(_testAPlusB_alValue1, _testAPlusB_alValue2);
        System.out.println("testAPlusB.result=" + _testAPlusB__return);


        }

        System.exit(0);
    }

}
