package com.smw.wsc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2016-06-06T16:41:21.869+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://tempurl.org", name = "salesSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SalesSoap {

    @WebResult(name = "postmalldailysalessummaryResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "postmalldailysalessummary", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Postmalldailysalessummary")
    @WebMethod(action = "http://tempurl.org/postmalldailysalessummary")
    @ResponseWrapper(localName = "postmalldailysalessummaryResponse", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.PostmalldailysalessummaryResponse")
    public com.smw.wsc.Postmalldailysalessummaryresponse2 postmalldailysalessummary(
        @WebParam(name = "astr_request", targetNamespace = "http://tempurl.org")
        com.smw.wsc.Postmalldailysalessummaryrequest astrRequest
    );

    @WebResult(name = "getcompanynameResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getcompanyname", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Getcompanyname")
    @WebMethod(action = "http://tempurl.org/getcompanyname")
    @ResponseWrapper(localName = "getcompanynameResponse", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.GetcompanynameResponse")
    public java.lang.String getcompanyname();

    @WebResult(name = "postsalescreateResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "postsalescreate", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Postsalescreate")
    @WebMethod(action = "http://tempurl.org/postsalescreate")
    @ResponseWrapper(localName = "postsalescreateResponse", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.PostsalescreateResponse")
    public com.smw.wsc.Postsalescreateresponse2 postsalescreate(
        @WebParam(name = "astr_request", targetNamespace = "http://tempurl.org")
        com.smw.wsc.Postsalescreaterequest astrRequest
    );

    @WebResult(name = "postesalescreateResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "postesalescreate", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Postesalescreate")
    @WebMethod(action = "http://tempurl.org/postesalescreate")
    @ResponseWrapper(localName = "postesalescreateResponse", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.PostesalescreateResponse")
    public com.smw.wsc.Postesalescreateresponse2 postesalescreate(
        @WebParam(name = "astr_request", targetNamespace = "http://tempurl.org")
        com.smw.wsc.Postesalescreaterequest astrRequest
    );

    @WebResult(name = "getversionResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getversion", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Getversion")
    @WebMethod(action = "http://tempurl.org/getversion")
    @ResponseWrapper(localName = "getversionResponse", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.GetversionResponse")
    public java.lang.String getversion();

    @WebResult(name = "postdailysalesestimatecreateResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "postdailysalesestimatecreate", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Postdailysalesestimatecreate")
    @WebMethod(action = "http://tempurl.org/postdailysalesestimatecreate")
    @ResponseWrapper(localName = "postdailysalesestimatecreateResponse", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.PostdailysalesestimatecreateResponse")
    public com.smw.wsc.Postdailysalesestimatecreateresponse2 postdailysalesestimatecreate(
        @WebParam(name = "astr_request", targetNamespace = "http://tempurl.org")
        com.smw.wsc.Postdailysalesestimatecreaterequest astrRequest
    );

    @WebResult(name = "postdailysalessummary2Result", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "postdailysalessummary2", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Postdailysalessummary2")
    @WebMethod(action = "http://tempurl.org/postdailysalessummary2")
    @ResponseWrapper(localName = "postdailysalessummary2Response", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.Postdailysalessummary2Response")
    public com.smw.wsc.Postdailysalessummary2Response2 postdailysalessummary2(
        @WebParam(name = "astr_request", targetNamespace = "http://tempurl.org")
        com.smw.wsc.Postdailysalessummary2Request astrRequest
    );

    @WebResult(name = "test_a_plus_bResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "test_a_plus_b", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.TestAPlusB")
    @WebMethod(operationName = "test_a_plus_b", action = "http://tempurl.org/test_a_plus_b")
    @ResponseWrapper(localName = "test_a_plus_bResponse", targetNamespace = "http://tempurl.org", className = "com.smw.wsc.TestAPlusBResponse")
    public int testAPlusB(
        @WebParam(name = "al_value1", targetNamespace = "http://tempurl.org")
        int alValue1,
        @WebParam(name = "al_value2", targetNamespace = "http://tempurl.org")
        int alValue2
    );
}
